import {
  Invoice,
  ClientProfile,
  PaymentTransaction,
  JobListing,
  JobApplication,
  Contract,
  TaxRecord,
  Dispute,
} from './types';

export const CURRENT_FREELANCER = {
  id: 'usr-freelancer-1',
  name: 'Chinedu Okafor',
  email: 'chinedu.codes@gmail.com',
  title: 'Senior Full-Stack Engineer & Product Designer',
  country: 'NG' as const,
  currency: 'NGN' as const,
  taxId: 'TIN-98421038-NG',
  bankAccount: {
    bankName: 'Access Bank',
    accountNumber: '0129482019',
    accountName: 'Chinedu E. Okafor',
  },
  rating: 4.95,
  completedProjects: 38,
  kycVerified: true,
};

export const CURRENT_CLIENT = {
  id: 'usr-client-1',
  name: 'Amara Sterling',
  company: 'FinPulse Systems Ltd',
  email: 'hiring@finpulsetechnologies.com',
  country: 'NG' as const,
  verified: true,
  rating: 4.9,
  totalSpent: 4200000,
};

export const INITIAL_CLIENTS: ClientProfile[] = [
  {
    id: 'cli-1',
    freelancerId: 'usr-freelancer-1',
    name: 'Amara Sterling',
    email: 'amara@finpulsetechnologies.com',
    companyName: 'FinPulse Systems Ltd',
    website: 'https://finpulsetechnologies.com',
    rating: 4.95,
    reviewCount: 14,
    paymentHistory: 'early',
    notes: 'Fintech startup in Victoria Island. Always pays within 24 hours of milestone approval.',
    totalBilled: 2450000,
    isVerified: true,
  },
  {
    id: 'cli-2',
    freelancerId: 'usr-freelancer-1',
    name: 'David Reynolds',
    email: 'david@meridianlabs.co.uk',
    companyName: 'Meridian Labs London',
    website: 'https://meridianlabs.co.uk',
    rating: 4.9,
    reviewCount: 9,
    paymentHistory: 'on_time',
    notes: 'UK healthtech client. Pays via international card or Stripe gateway.',
    totalBilled: 1800000,
    isVerified: true,
  },
  {
    id: 'cli-3',
    freelancerId: 'usr-freelancer-1',
    name: 'Tolani Adeleke',
    email: 'tolani@zuri-app.io',
    companyName: 'Zuri Mobile Commerce',
    website: 'https://zuri-app.io',
    rating: 4.6,
    reviewCount: 6,
    paymentHistory: 'on_time',
    notes: 'Series A marketplace. Requires formal Wht/Tax withholding invoice format.',
    totalBilled: 950000,
    isVerified: true,
  },
  {
    id: 'cli-4',
    freelancerId: 'usr-freelancer-1',
    name: 'Marcus Vance',
    email: 'marcus@vancegrowth.com',
    companyName: 'Vance Digital US',
    website: 'https://vancegrowth.com',
    rating: 3.8,
    reviewCount: 4,
    paymentHistory: 'late',
    notes: 'Tends to lag on net-14 payment. Needs automated reminder emails.',
    totalBilled: 600000,
    isVerified: false,
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-001',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    freelancerEmail: 'chinedu.codes@gmail.com',
    freelancerBank: {
      bankName: 'Access Bank',
      accountNumber: '0129482019',
      accountName: 'Chinedu E. Okafor',
    },
    clientId: 'cli-1',
    clientName: 'Amara Sterling',
    clientEmail: 'amara@finpulsetechnologies.com',
    clientCompany: 'FinPulse Systems Ltd',
    amount: 850000,
    currency: 'NGN',
    status: 'paid',
    issueDate: '2026-09-02',
    dueDate: '2026-09-16',
    paidAt: '2026-09-04T11:20:00Z',
    description: 'Sprint 1: Core Wallet Integration & Paystack Virtual Account Engine',
    lineItems: [
      {
        id: 'li-1',
        description: 'Webhook architecture & reconciliation state machine',
        quantity: 1,
        rate: 450000,
        amount: 450000,
      },
      {
        id: 'li-2',
        description: 'Next.js App Router transaction history & export component',
        quantity: 1,
        rate: 400000,
        amount: 400000,
      },
    ],
    notes: 'Thank you for your business. Payment received through Paystack Instant Checkout.',
    paystackReference: 'PSTK_984219385923',
    processingFee: 12750,
    netAmount: 837250,
    reminderSentCount: 0,
    createdAt: '2026-09-02T09:00:00Z',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-002',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    freelancerEmail: 'chinedu.codes@gmail.com',
    freelancerBank: {
      bankName: 'Access Bank',
      accountNumber: '0129482019',
      accountName: 'Chinedu E. Okafor',
    },
    clientId: 'cli-2',
    clientName: 'David Reynolds',
    clientEmail: 'david@meridianlabs.co.uk',
    clientCompany: 'Meridian Labs London',
    amount: 950000,
    currency: 'NGN',
    status: 'paid',
    issueDate: '2026-09-10',
    dueDate: '2026-09-24',
    paidAt: '2026-09-12T15:45:00Z',
    description: 'Biometric Telehealth UI Redesign & Mobile Responsive Layout',
    lineItems: [
      {
        id: 'li-3',
        description: 'Tailwind design system & theme token configuration',
        quantity: 1,
        rate: 350000,
        amount: 350000,
      },
      {
        id: 'li-4',
        description: 'Patient appointment scheduling and live calendar module',
        quantity: 1,
        rate: 600000,
        amount: 600000,
      },
    ],
    notes: 'Includes 2 rounds of review as agreed in Contract #CON-2026-08.',
    paystackReference: 'PSTK_771829034120',
    processingFee: 14250,
    netAmount: 935750,
    reminderSentCount: 0,
    createdAt: '2026-09-10T10:30:00Z',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-003',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    freelancerEmail: 'chinedu.codes@gmail.com',
    freelancerBank: {
      bankName: 'Access Bank',
      accountNumber: '0129482019',
      accountName: 'Chinedu E. Okafor',
    },
    clientId: 'cli-1',
    clientName: 'Amara Sterling',
    clientEmail: 'amara@finpulsetechnologies.com',
    clientCompany: 'FinPulse Systems Ltd',
    amount: 650000,
    currency: 'NGN',
    status: 'sent',
    issueDate: '2026-09-20',
    dueDate: '2026-10-04',
    description: 'Sprint 2: Real-time Analytics Dashboard & Audit Logging API',
    lineItems: [
      {
        id: 'li-5',
        description: 'Real-time telemetry event bus and cache invalidation',
        quantity: 1,
        rate: 350000,
        amount: 350000,
      },
      {
        id: 'li-6',
        description: 'Role-based access control (RBAC) middleware & security tests',
        quantity: 1,
        rate: 300000,
        amount: 300000,
      },
    ],
    notes: 'Due in 9 days. Pay easily with debit card or Nigerian bank transfer via Paystack.',
    paystackReference: 'PSTK_PEND_9102931',
    processingFee: 9750,
    netAmount: 640250,
    reminderSentCount: 0,
    createdAt: '2026-09-20T08:15:00Z',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-004',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    freelancerEmail: 'chinedu.codes@gmail.com',
    freelancerBank: {
      bankName: 'Access Bank',
      accountNumber: '0129482019',
      accountName: 'Chinedu E. Okafor',
    },
    clientId: 'cli-4',
    clientName: 'Marcus Vance',
    clientEmail: 'marcus@vancegrowth.com',
    clientCompany: 'Vance Digital US',
    amount: 450000,
    currency: 'NGN',
    status: 'overdue',
    issueDate: '2026-08-25',
    dueDate: '2026-09-10',
    description: 'Landing Page Conversion Optimization & Performance Audit',
    lineItems: [
      {
        id: 'li-7',
        description: 'Next.js 15 bundle size optimization (Lighthouse 96+)',
        quantity: 1,
        rate: 250000,
        amount: 250000,
      },
      {
        id: 'li-8',
        description: 'Interactive pricing calculator with dynamic currency toggle',
        quantity: 1,
        rate: 200000,
        amount: 200000,
      },
    ],
    notes: 'Invoice is 15 days overdue. Automatic late payment reminder dispatched.',
    paystackReference: 'PSTK_OVERDUE_0029',
    processingFee: 6750,
    netAmount: 443250,
    reminderSentCount: 2,
    lastReminderDate: '2026-09-17',
    createdAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'inv-105',
    invoiceNumber: 'INV-2026-005',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    freelancerEmail: 'chinedu.codes@gmail.com',
    freelancerBank: {
      bankName: 'Access Bank',
      accountNumber: '0129482019',
      accountName: 'Chinedu E. Okafor',
    },
    clientId: 'cli-3',
    clientName: 'Tolani Adeleke',
    clientEmail: 'tolani@zuri-app.io',
    clientCompany: 'Zuri Mobile Commerce',
    amount: 550000,
    currency: 'NGN',
    status: 'draft',
    issueDate: '2026-09-24',
    dueDate: '2026-10-08',
    description: 'Cart abandonment push notification engine & background jobs',
    lineItems: [
      {
        id: 'li-9',
        description: 'Automated discount recovery workflow',
        quantity: 1,
        rate: 300000,
        amount: 300000,
      },
      {
        id: 'li-10',
        description: 'SMS & WhatsApp template integration',
        quantity: 1,
        rate: 250000,
        amount: 250000,
      },
    ],
    notes: 'Draft stage. Ready for client review before formal dispatch.',
    reminderSentCount: 0,
    createdAt: '2026-09-24T16:00:00Z',
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'pay-201',
    invoiceId: 'inv-101',
    invoiceNumber: 'INV-2026-001',
    freelancerId: 'usr-freelancer-1',
    amount: 850000,
    currency: 'NGN',
    status: 'success',
    paymentMethod: 'paystack',
    processorReference: 'PSTK_984219385923',
    processingFee: 12750,
    netAmount: 837250,
    payoutStatus: 'paid',
    payoutDate: '2026-09-05T08:00:00Z',
    paidBy: 'Amara Sterling (FinPulse Systems)',
    createdAt: '2026-09-04T11:20:00Z',
  },
  {
    id: 'pay-202',
    invoiceId: 'inv-102',
    invoiceNumber: 'INV-2026-002',
    freelancerId: 'usr-freelancer-1',
    amount: 950000,
    currency: 'NGN',
    status: 'success',
    paymentMethod: 'card',
    processorReference: 'PSTK_771829034120',
    processingFee: 14250,
    netAmount: 935750,
    payoutStatus: 'paid',
    payoutDate: '2026-09-13T09:30:00Z',
    paidBy: 'David Reynolds (Meridian Labs)',
    createdAt: '2026-09-12T15:45:00Z',
  },
];

export const INITIAL_JOBS: JobListing[] = [
  {
    id: 'job-1',
    clientId: 'cli-1',
    clientName: 'Amara Sterling',
    clientCompany: 'FinPulse Systems Ltd',
    clientVerified: true,
    clientRating: 4.95,
    clientPaymentHistory: 'early',
    title: 'Senior Next.js 15 Architect for Escrow & Dispute Microservice',
    description:
      'We require an experienced developer to architect an automated escrow holdback engine. Must have deep understanding of Webhooks, idempotent event handling, and security hardening. Budget funded in FreelancePay Escrow.',
    category: 'Engineering',
    budgetMin: 1200000,
    budgetMax: 1800000,
    currency: 'NGN',
    status: 'open',
    requiredSkills: ['Next.js', 'TypeScript', 'Paystack API', 'PostgreSQL', 'Tailwind CSS'],
    experienceLevel: 'expert',
    timeline: '3-4 weeks',
    applicationsCount: 4,
    createdAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'job-2',
    clientId: 'cli-2',
    clientName: 'David Reynolds',
    clientCompany: 'Meridian Labs London',
    clientVerified: true,
    clientRating: 4.9,
    clientPaymentHistory: 'on_time',
    title: 'Design System & Figma Component Library for HealthTech Platform',
    description:
      'Looking for a product designer with a sharp eye for accessible, WCAG AA typography and clean dashboard UI. Will work with our London team asynchronously to deliver 24 interactive views.',
    category: 'Design',
    budgetMin: 800000,
    budgetMax: 1200000,
    currency: 'NGN',
    status: 'open',
    requiredSkills: ['Figma', 'Design Systems', 'WCAG Accessibility', 'User Research'],
    experienceLevel: 'intermediate',
    timeline: '2-3 weeks',
    applicationsCount: 7,
    createdAt: '2026-09-21T14:30:00Z',
  },
  {
    id: 'job-3',
    clientId: 'cli-3',
    clientName: 'Tolani Adeleke',
    clientCompany: 'Zuri Mobile Commerce',
    clientVerified: true,
    clientRating: 4.6,
    clientPaymentHistory: 'on_time',
    title: 'B2B Technical Content Writer - FinTech & Open Banking in Africa',
    description:
      'Create 4 comprehensive long-form whitepapers and technical guides explaining CBN regulatory compliance, cross-border remittance, and payment gateway APIs for founders.',
    category: 'Writing',
    budgetMin: 400000,
    budgetMax: 650000,
    currency: 'NGN',
    status: 'open',
    requiredSkills: ['Technical Writing', 'Fintech', 'SEO', 'Whitepapers'],
    experienceLevel: 'intermediate',
    timeline: '2 weeks',
    applicationsCount: 11,
    createdAt: '2026-09-19T08:00:00Z',
  },
];

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: 'app-1',
    jobId: 'job-1',
    jobTitle: 'Senior Next.js 15 Architect for Escrow & Dispute Microservice',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    freelancerEmail: 'chinedu.codes@gmail.com',
    freelancerRating: 4.95,
    proposalText:
      'I have built 4 enterprise payment systems with Paystack and Flutterwave handling over ₦250M in volume. My proposed architecture will utilize idempotent webhook workers and zero-pill clean UI.',
    proposedRate: 1500000,
    currency: 'NGN',
    portfolioUrl: 'https://github.com/chinedu-dev',
    status: 'shortlisted',
    createdAt: '2026-09-23T09:12:00Z',
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'con-301',
    jobId: 'job-1',
    title: 'FinPulse Core Wallet & Reconciliation Engine',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    clientId: 'cli-1',
    clientName: 'Amara Sterling',
    templateType: 'development',
    totalAmount: 1500000,
    currency: 'NGN',
    startDate: '2026-09-01',
    endDate: '2026-10-15',
    revisionLimit: 2,
    revisionsUsed: 1,
    status: 'active',
    signedByFreelancer: true,
    signedByClient: true,
    freelancerSignature: 'Chinedu Okafor',
    clientSignature: 'Amara Sterling',
    signedAt: '2026-09-01T14:00:00Z',
    scopeSummary:
      'Complete end-to-end development of Paystack virtual account generation, automated ledger bookkeeping, and responsive dashboard.',
    legalTerms:
      'All IP rights transfer to Client upon full milestone settlement. FreelancePay holds funds in Escrow until client deliverable verification.',
    milestones: [
      {
        id: 'ms-1',
        contractId: 'con-301',
        title: 'Milestone 1: Webhook receiver & database schemas',
        description: 'Setup Supabase tables, RLS policies, and Paystack signature verification.',
        amount: 750000,
        percentage: 50,
        dueDate: '2026-09-15',
        status: 'approved',
        deliverableLink: 'https://github.com/finpulse/core-api/pull/12',
        deliverableNotes: 'Passed all 42 automated integration tests.',
        submittedAt: '2026-09-14T10:00:00Z',
        approvedAt: '2026-09-15T16:30:00Z',
      },
      {
        id: 'ms-2',
        contractId: 'con-301',
        title: 'Milestone 2: Production UI & reconciliation report generator',
        description: 'Frontend dashboard with CSV/PDF ledger export and user security testing.',
        amount: 750000,
        percentage: 50,
        dueDate: '2026-10-15',
        status: 'in_progress',
      },
    ],
  },
];

export const INITIAL_TAX_RECORD: TaxRecord = {
  year: 2026,
  country: 'NG',
  currency: 'NGN',
  grossIncome: 1800000, // Total paid invoices so far
  totalDeductions: 450000,
  taxableIncome: 1350000,
  estimatedTax: 270000, // 20% flat tax on taxable freelance profits
  effectiveRate: 15.0,
  deductions: [
    {
      id: 'ded-1',
      category: 'Utilities & Internet',
      description: 'Starlink High-Speed Satellite Internet Subscription (6 months)',
      amount: 228000,
      date: '2026-07-15',
    },
    {
      id: 'ded-2',
      category: 'Power & Fuel',
      description: 'Generator fuel & solar inverter battery maintenance for work desk',
      amount: 140000,
      date: '2026-08-01',
    },
    {
      id: 'ded-3',
      category: 'Software & Tools',
      description: 'Figma Pro + GitHub Copilot + Cursor yearly software subscription',
      amount: 82000,
      date: '2026-06-20',
    },
  ],
};

export const INITIAL_DISPUTES: Dispute[] = [
  {
    id: 'disp-501',
    contractId: 'con-301',
    contractTitle: 'FinPulse Core Wallet & Reconciliation Engine',
    freelancerId: 'usr-freelancer-1',
    freelancerName: 'Chinedu Okafor',
    clientId: 'cli-4',
    clientName: 'Marcus Vance',
    amount: 150000,
    currency: 'NGN',
    reason: 'Unapproved Scope Creep & Additional Mobile Screen Requests',
    freelancerStatement:
      'Client requested 5 additional custom dashboard widgets not listed in the signed contract scope, exceeding the agreed 2 revision limit.',
    clientStatement:
      'We assumed the additional mobile views were included in the standard responsive breakdown.',
    status: 'under_review',
    resolutionDetails: 'Admin mediator scheduled 24-hr resolution review. Escrow remains held.',
    createdAt: '2026-09-23T11:00:00Z',
  },
];
